Axipi\CoreBundle\Entity\Attribute:
    type: entity
    table: attribute
    indexes:
        IDX_FA7AEFFBE9ED820C:
            columns:
                - block_id
    uniqueConstraints:
        block_id_code:
            columns:
                - block_id
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        isRequired:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_required
        isUpload:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_upload
        isRich:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_rich
        isSearch:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_search
        ordering:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
    manyToOne:
        block:
            targetEntity: Block
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                block_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
