Axipi\CoreBundle\Entity\Comment:
    repositoryClass: Axipi\CoreBundle\Repository\CommentRepository
    type: entity
    table: comment
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        author:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        website:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        message:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        isActive:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_active
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
    manyToOne:
        item:
            targetEntity: Item
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                item_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
    lifecycleCallbacks: {  }
