Axipi\CoreBundle\Entity\Component:
    repositoryClass: Axipi\CoreBundle\Repository\ComponentRepository
    type: entity
    table: component
    uniqueConstraints:
        service:
            columns:
                - service
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        category:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        zoneId:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: zone_id
        service:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        parent:
            type: integer
            nullable: true
            options:
                unsigned: true
        icon:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        isUnique:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_unique
        isSearch:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_search
        isSitemap:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_sitemap
        isActive:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_active
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
    lifecycleCallbacks: {  }
