Axipi\CoreBundle\Entity\Component:
    repositoryClass: Axipi\CoreBundle\Repository\ComponentRepository
    type: entity
    table: component
    indexes:
        parent:
            columns:
                - parent
        zone_id:
            columns:
                - zone_id
    uniqueConstraints:
        service:
            columns:
                - service
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        category:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        service:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        template:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        icon:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        isUnique:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_unique
        isSearch:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_search
        isSitemap:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_sitemap
        isActive:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_active
        attributesSchema:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: attributes_schema
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
    lifecycleCallbacks: {  }
    manyToOne:
        parent:
            targetEntity: Component
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent:
                    referencedColumnName: id
                    onDelete: "set null"
            orphanRemoval: false
        zone:
            targetEntity: Zone
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                zone_id:
                    referencedColumnName: id
                    onDelete: "set null"
            orphanRemoval: false
