Axipi\CoreBundle\Entity\Item:
    repositoryClass: Axipi\CoreBundle\Repository\ItemRepository
    type: entity
    table: item
    indexes:
        component_id:
            columns:
                - component_id
        zone_id:
            columns:
                - zone_id
        parent:
            columns:
                - parent
        language_id:
            columns:
                - language_id
    uniqueConstraints:
        language_id_code:
            columns:
                - language_id
                - code
        language_id_slug:
            columns:
                - language_id
                - slug
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        code:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        slug:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        template:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        titleSeo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: title_seo
        descriptionSeo:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: description_seo
        style:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        meta:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        script:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        titleSocial:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: title_social
        descriptionSocial:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: description_social
        isHome:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_home
        excludeSearch:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: exclude_search
        excludeSitemap:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: exclude_sitemap
        isActive:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_active
        ordering:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        attributes:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
    manyToOne:
        component:
            targetEntity: Component
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                component_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
        language:
            targetEntity: Language
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                language_id:
                    nullable: true
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
        parent:
            targetEntity: Item
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: "children"
            joinColumns:
                parent:
                    nullable: true
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
        zone:
            targetEntity: Zone
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: widgets
            joinColumns:
                zone_id:
                    nullable: true
                    referencedColumnName: id
                    onDelete: "set null"
            orphanRemoval: false
    oneToMany:
        children:
            targetEntity: Item
            mappedBy: parent
    lifecycleCallbacks: {  }
