Axipi\CoreBundle\Entity\Page:
    repositoryClass: Axipi\CoreBundle\Repository\PageRepository
    type: entity
    table: page
    indexes:
        component_id:
            columns:
                - component_id
        parent:
            columns:
                - parent
        IDX_140AB6203EB8070A:
            columns:
                - program_id
    uniqueConstraints:
        program_id_code:
            columns:
                - program_id
                - code
        program_id_slug:
            columns:
                - program_id
                - slug
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        code:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        slug:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        titleSeo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: title_seo
        descriptionSeo:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: description_seo
        metaRobots:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: meta_robots
        isActive:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_active
        ordering:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        attributes:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
    manyToOne:
        parent:
            targetEntity: Page
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent:
                    referencedColumnName: id
            orphanRemoval: false
        component:
            targetEntity: Component
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                component_id:
                    nullable: false
                    referencedColumnName: id
            orphanRemoval: false
        program:
            targetEntity: Program
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                program_id:
                    nullable: false
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
