Axipi\CoreBundle\Entity\Program:
    type: entity
    table: program
    indexes:
        language_id:
            columns:
                - language_id
        country_id:
            columns:
                - country_id
    uniqueConstraints:
        language_id_country_id:
            columns:
                - language_id
                - country_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descriptionSeo:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: description_seo
        timezone:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        isDefault:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_default
        hasMaintenance:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: has_maintenance
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
    manyToOne:
        country:
            targetEntity: Country
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                country_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
        language:
            targetEntity: Language
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                language_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
    lifecycleCallbacks: {  }
