Axipi\CoreBundle\Entity\RolePermission:
    type: entity
    table: role_permission
    indexes:
        role_id:
            columns:
                - role_id
        permission_id:
            columns:
                - permission_id
    uniqueConstraints:
        role_id_permission_id:
            columns:
                - role_id
                - permission_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
    manyToOne:
        role:
            targetEntity: Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_id:
                    referencedColumnName: id
            orphanRemoval: false
        permission:
            targetEntity: Permission
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                permission_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
