Axipi\CoreBundle\Entity\User:
    repositoryClass: Axipi\CoreBundle\Repository\UserRepository
    type: entity
    table: user
    uniqueConstraints:
        username:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 60
            options:
                fixed: true
        firstname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lastname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        isAuthorized:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_authorized
        roles:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
    lifecycleCallbacks: {  }
