Axipi\CoreBundle\Entity\Zone:
    repositoryClass: Axipi\CoreBundle\Repository\ZoneRepository
    type: entity
    table: zone
    uniqueConstraints:
        code:
            columns:
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        ordering:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        isActive:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_active
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
    oneToMany:
        components:
            targetEntity: Axipi\CoreBundle\Entity\Component
            mappedBy: "zone"
            cascade: [ "persist" ]
            orderBy:
                title: ASC
        widgets:
            targetEntity: Axipi\CoreBundle\Entity\Item
            mappedBy: "zone"
            cascade: [ "persist" ]
            orderBy:
                ordering: ASC
                title: ASC
    lifecycleCallbacks: {  }
