axipi_core_home:
    path:  /
    defaults:
        _controller: "axipi_core_controller_default:indexAction"
        slug: ""

axipi_core_slug:
    path:  /{slug}
    defaults:
        _controller: "axipi_core_controller_default:indexAction"
    requirements:
        slug: ".+"
