services:
    axipi_core_widget_abstract:
        class: Axipi\CoreBundle\Widget\AbstractWidget
        abstract: true
        calls:
            - [ "setContainer", [ "@service_container" ] ]

    axipi_core_controller_abstract:
        class: Axipi\CoreBundle\Controller\AbstractController
        abstract: true
        calls:
            - [ "setContainer", [ "@service_container" ] ]

    axipi_core_controller_default:
        class: Axipi\CoreBundle\Controller\DefaultController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_core_manager_core"

    axipi_core_manager_abstract:
        class: Axipi\CoreBundle\Manager\AbstractManager
        abstract: true
        calls:
            - [ "setEntityManager", [ "@doctrine.orm.entity_manager" ] ]

    axipi_core_manager_core:
        class: Axipi\CoreBundle\Manager\CoreManager
        parent: "axipi_core_manager_abstract"

    axipi_core_twig_extension_core:
        class: Axipi\CoreBundle\Twig\Extension\CoreExtension
        calls:
          - [ "setContainer", [ "@service_container" ] ]
          - [ "setEntityManager", [ "@doctrine.orm.entity_manager"] ]
        tags:
            -  { name: twig.extension }
