front_slash:
    path:  /
    defaults:
        _controller: "core.controller:indexAction"
        slug: ""

front_catch_all:
    path:  /{slug}
    defaults:
        _controller: "core.controller:indexAction"
    requirements:
        slug: ".+"
