services:
    core.widget.abstract:
        class: Project29k\CoreBundle\Widget\AbstractWidget
        abstract: true
        calls:
            - [ "setContainer", [ "@service_container" ] ]

    core.controller.abstract:
        class: Project29k\CoreBundle\Controller\AbstractController
        abstract: true
        calls:
            - [ "setContainer", [ "@service_container" ] ]

    core.controller:
        parent: "core.controller.abstract"
        class: Project29k\CoreBundle\Controller\DefaultController
        arguments:
            - "@core.manager"

    core.manager.abstract:
        class: Project29k\CoreBundle\Manager\AbstractManager
        abstract: true
        calls:
            - [ "setEntityManager", [ "@doctrine.orm.entity_manager" ] ]

    core.manager:
        class: Project29k\CoreBundle\Manager\CoreManager

    core.twig.extension:
        class: Project29k\CoreBundle\Twig\Extension\CoreExtension
        calls:
          - [ "setContainer", [ "@service_container" ] ]
          - [ "setEntityManager", [ "@doctrine.orm.entity_manager"] ]
        tags:
            -  { name: twig.extension }
