services:
    core.controller:
        class: Project29k\CoreBundle\Controller\DefaultController
        arguments:
            - "@core.manager"
        calls:
            - [ "setHttpKernel", [ "@http_kernel" ] ]
            - [ "setRequestStack", [ "@request_stack" ] ]

    core.manager.abstract:
        class: Project29k\CoreBundle\Manager\AbstractManager
        abstract: true
        calls:
            - [ "setEntityManager", [ "@doctrine.orm.entity_manager" ] ]

    core.manager:
        class: Project29k\CoreBundle\Manager\CoreManager
        public: false

    core.object.repository:
        class: Project29k\CoreBundle\Repository\CoreRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ 'CoreBundle:Object' ]

    core.content_controller:
        class: Project29k\CoreBundle\Controller\ContentController
        calls:
            - [ "setEngineInterface", [ "@templating" ] ]

    core.twig.extension:
        class: Project29k\CoreBundle\Twig\Extension\CoreExtension
        calls:
          - [ "setEntityManager", [ "@doctrine.orm.entity_manager"] ]
        tags:
            -  { name: twig.extension }
