services:
    axipi_app_controller_example:
        class: Axipi\AppBundle\Controller\ExampleController
        parent: "axipi_core_widget_abstract"

    axipi_app_widget_example:
        class: Axipi\AppBundle\Widget\ExampleWidget
        parent: "axipi_core_widget_abstract"
