_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

AxipiBackendBundle:
    resource: "@AxipiBackendBundle/Resources/config/routing.yml"
    prefix: "/backend"
    defaults:
        _locale: "en"

AxipiCoreBundle:
    resource: "@AxipiCoreBundle/Resources/config/routing.yml"
    prefix: "/"
