AxipiBackendBundle:
    resource: "@AxipiBackendBundle/Resources/config/routing.yml"
    prefix: "/backend"

AxipiCoreBundle:
    resource: "@AxipiCoreBundle/Resources/config/routing.yml"
    prefix: "/"
