# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        default_provider:
            entity:
                class: AxipiCoreBundle:User
                property: email

    firewalls:
        backend_login:
            pattern: ^/backend/login$
            anonymous:  ~

        backend:
            pattern:   ^/backend
            form_login:
                username_parameter: email
                password_parameter: password
                login_path: axipi_backend_login
                check_path: axipi_backend_login_check
                always_use_default_target_path: true
                default_target_path: axipi_backend_home
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: axipi_backend_logout
                target: axipi_backend_login

    encoders:
        Axipi\CoreBundle\Entity\User:
            algorithm: bcrypt
