security:
    providers:
        axipi_core_provider:
            entity:
                class: Axipi\CoreBundle\Entity\User
                property: username

    firewalls:
        axipi_backend_login:
            pattern: ^/backend/login$
            anonymous:  ~

        axipi_backend:
            pattern:   ^/backend
            provider: axipi_core_provider
            form_login:
                username_parameter: username
                password_parameter: password
                login_path: axipi_backend_login
                check_path: axipi_backend_login_check
                always_use_default_target_path: true
                default_target_path: axipi_backend_home
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: axipi_backend_logout
                target: axipi_backend_login

    encoders:
        Axipi\CoreBundle\Entity\User:
            algorithm: bcrypt
