security:
    providers:
        axipi_core_provider:
            entity:
                class: Axipi\CoreBundle\Entity\User
                property: username

    firewalls:
        axipi_backend:
            pattern:   ^/
            provider: axipi_core_provider
            form_login:
                username_parameter: username
                password_parameter: password
                login_path: axipi_backend_login
                check_path: axipi_backend_login_check
                always_use_default_target_path: true
                default_target_path: axipi_backend_home
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: axipi_backend_logout
                target: axipi_backend_login
            security: true
            anonymous: true

    access_control:
        - { path: "^/backend/login", roles: "IS_AUTHENTICATED_ANONYMOUSLY" }
        - { path: "^/backend", roles: "IS_AUTHENTICATED_FULLY" }
        - { path: "^/.*", roles: "IS_AUTHENTICATED_ANONYMOUSLY" }

    encoders:
        Axipi\CoreBundle\Entity\User:
            algorithm: bcrypt
