services:
    axipi_blog_controller_blog:
        class: Axipi\BlogBundle\Controller\BlogController
        parent: "axipi_core_controller_abstract"

    axipi_blog_controller_category:
        class: Axipi\BlogBundle\Controller\CategoryController
        parent: "axipi_core_controller_abstract"

    axipi_blog_controller_post:
        class: Axipi\BlogBundle\Controller\PostController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_core_manager_comment"
            - "%google_recaptcha_sitekey%"

    axipi_blog_widget_categories:
        class: Axipi\BlogBundle\Widget\CategoriesWidget
        parent: "axipi_core_widget_abstract"
