CoreBundle\Entity\Attribute:
    type: entity
    table: attribute
    indexes:
        IDX_FA7AEFFBE9ED820C:
            columns:
                - block_id
    uniqueConstraints:
        block_id_code:
            columns:
                - block_id
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        upload:
            type: boolean
            nullable: false
            options:
                default: '0'
        rich:
            type: boolean
            nullable: false
            options:
                default: '0'
        required:
            type: boolean
            nullable: false
            options:
                default: '0'
        search:
            type: boolean
            nullable: false
            options:
                default: '0'
        ordering:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        datecreated:
            type: datetime
            nullable: false
    manyToOne:
        block:
            targetEntity: Block
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                block_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
