Project29k\CoreBundle\Entity\Country:
    type: entity
    table: country
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        datecreated:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
