CoreBundle\Entity\Object:
    type: entity
    table: object
    indexes:
        type_id:
            columns:
                - type_id
        parent:
            columns:
                - parent
        zone_id:
            columns:
                - zone_id
        IDX_A8ADABEC3EB8070A:
            columns:
                - program_id
    uniqueConstraints:
        program_id_code:
            columns:
                - program_id
                - code
        program_id_slug:
            columns:
                - program_id
                - slug
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        code:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        slug:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        titleSeo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: title_seo
        descriptionSeo:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: description_seo
        robots:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '0'
        ordering:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        datecreated:
            type: datetime
            nullable: false
    manyToOne:
        zone:
            targetEntity: Zone
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                zone_id:
                    referencedColumnName: id
            orphanRemoval: false
        parent:
            targetEntity: Object
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent:
                    referencedColumnName: id
            orphanRemoval: false
        type:
            targetEntity: Type
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_id:
                    referencedColumnName: id
            orphanRemoval: false
        program:
            targetEntity: Program
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                program_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
