CoreBundle\Entity\Program:
    type: entity
    table: program
    indexes:
        country_id:
            columns:
                - country_id
        language_id:
            columns:
                - language_id
    uniqueConstraints:
        country_id_language_id:
            columns:
                - country_id
                - language_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        timezone:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        default:
            type: boolean
            nullable: false
            options:
                default: '0'
        maintenance:
            type: boolean
            nullable: false
            options:
                default: '0'
        datecreated:
            type: datetime
            nullable: false
    manyToOne:
        country:
            targetEntity: Country
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                country_id:
                    referencedColumnName: id
            orphanRemoval: false
        language:
            targetEntity: Language
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                language_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
