CoreBundle\Entity\Relation:
    type: entity
    table: relation
    uniqueConstraints:
        obj_id_rel_target:
            columns:
                - obj_id
                - rel_target
    id:
        relId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: rel_id
            generator:
                strategy: IDENTITY
    fields:
        objId:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: obj_id
        relTarget:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: rel_target
        relTitle:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: rel_title
        relActive:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: rel_active
        relOrdering:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: rel_ordering
        relDatecreated:
            type: datetime
            nullable: false
            column: rel_datecreated
    lifecycleCallbacks: {  }
