Project29k\CoreBundle\Entity\Relation:
    type: entity
    table: relation
    indexes:
        target:
            columns:
                - target
        IDX_62894749232D562B:
            columns:
                - object_id
    uniqueConstraints:
        object_id_target:
            columns:
                - object_id
                - target
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        isActive:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_active
        ordering:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        datecreated:
            type: datetime
            nullable: false
    manyToOne:
        object:
            targetEntity: Object
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                object_id:
                    referencedColumnName: id
            orphanRemoval: false
        target:
            targetEntity: Object
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                target:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
