Project29k\CoreBundle\Entity\Role:
    type: entity
    table: role
    uniqueConstraints:
        code:
            columns:
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        datecreated:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
