Project29k\CoreBundle\Entity\Type:
    repositoryClass: Project29k\CoreBundle\Repository\TypeRepository
    type: entity
    table: type
    indexes:
        IDX_8CDE5729BCF5E72D:
            columns:
                - category_id
    uniqueConstraints:
        category_id_code:
            columns:
                - category_id
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        zoneId:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: zone_id
        controllerAlias:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: controller_alias
        code:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        parent:
            type: integer
            nullable: true
            options:
                unsigned: true
        icon:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        isUnique:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_unique
        isSearch:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_search
        isSitemap:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_sitemap
        isActive:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_active
        datecreated:
            type: datetime
            nullable: false
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
