Project29k\CoreBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 40
            options:
                fixed: true
        firstname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lastname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        isAuthorized:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_authorized
        datecreated:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
