CoreBundle\Entity\Zone:
    type: entity
    table: zone
    uniqueConstraints:
        code:
            columns:
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '0'
        datecreated:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
