axipi_backend_login:
    path:  /login
    defaults:
        _controller: "axipi_backend_controller_login:indexAction"

axipi_backend_login_check:
    path: /login_check

axipi_backend_logout:
    path: /logout

axipi_backend_home:
    path:  /
    defaults:
        _controller: "axipi_backend_controller_home:indexAction"

axipi_backend_components:
    path:  /components/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_component:dispatchAction"
        action: "index"
        id: null

axipi_backend_pages:
    path:  /pages/{mode}/{language}/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_page:dispatchAction"
        mode: "normal"
        language: "xx"
        action: "index"
        id: null

axipi_backend_widgets:
    path:  /widgets/{language}/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_widget:dispatchAction"
        language: "xx"
        action: "index"
        id: null

axipi_backend_relations:
    path:  /relations/{language}/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_relation:dispatchAction"
        language: "xx"
        action: "index"
        id: null

axipi_backend_zones:
    path:  /zones/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_zone:dispatchAction"
        action: "index"
        id: null

axipi_backend_languages:
    path:  /languages/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_language:dispatchAction"
        action: "index"
        id: null

axipi_backend_users:
    path:  /users/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_user:dispatchAction"
        action: "index"
        id: null

axipi_backend_profile:
    path:  /profile/{action}
    defaults:
        _controller: "axipi_backend_controller_profile:dispatchAction"
        action: "read"

axipi_backend_files:
    path:  /files/{mode}/{action}/{slug}
    defaults:
        _controller: "axipi_backend_controller_file:dispatchAction"
        mode: "normal"
        action: "index"
        slug: ""
    requirements:
        slug: ".+"

axipi_backend_search:
    path:  /search/{action}
    defaults:
        _controller: "axipi_backend_controller_search:dispatchAction"
        action: "index"

axipi_backend_cache:
    path:  /cache/{action}
    defaults:
        _controller: "axipi_backend_controller_cache:dispatchAction"
        action: "index"

axipi_backend_info:
    path:  /info/{action}
    defaults:
        _controller: "axipi_backend_controller_info:dispatchAction"
        action: "index"
