axipi_backend_login:
    path:  /login
    defaults:
        _controller: "axipi_backend_controller_login:indexAction"

axipi_backend_login_check:
    path: /login_check
    defaults:
        _locale: "en"

axipi_backend_logout:
    path: /logout

axipi_backend_home:
    path:  /
    defaults:
        _controller: "axipi_backend_controller_home:indexAction"

axipi_backend_component:
    path:  /component/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_component:dispatchAction"
        action: "index"
        id: null

axipi_backend_page:
    path:  /page/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_page:dispatchAction"
        action: "index"
        id: null

axipi_backend_widget:
    path:  /widget/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_widget:dispatchAction"
        action: "index"
        id: null

axipi_backend_widget_page:
    path:  /widget_page/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_widget_page:dispatchAction"
        action: "index"
        id: null

axipi_backend_zone:
    path:  /zone/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_zone:dispatchAction"
        action: "index"
        id: null

axipi_backend_language:
    path:  /language/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_language:dispatchAction"
        action: "index"
        id: null

axipi_backend_user:
    path:  /user/{action}/{id}
    defaults:
        _controller: "axipi_backend_controller_user:dispatchAction"
        action: "index"
        id: null
