services:
    axipi_backend_controller_login:
        class: Axipi\BackendBundle\Controller\LoginController
        parent: "axipi_core_controller_abstract"

    axipi_backend_controller_home:
        class: Axipi\BackendBundle\Controller\HomeController
        parent: "axipi_core_controller_abstract"

    axipi_backend_controller_profile:
        class: Axipi\BackendBundle\Controller\ProfileController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_core_manager_user"

    axipi_backend_controller_search:
        class: Axipi\BackendBundle\Controller\SearchController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_search_manager_search"

    axipi_backend_controller_cache:
        class: Axipi\BackendBundle\Controller\CacheController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_core_manager_cache"

    axipi_backend_controller_component:
        class: Axipi\BackendBundle\Controller\ComponentController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_core_manager_component"
            - "@axipi_core_manager_zone"

    axipi_backend_controller_page:
        class: Axipi\BackendBundle\Controller\PageController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_core_manager_item"
            - "@axipi_core_manager_language"
            - "@axipi_core_manager_component"

    axipi_backend_controller_widget:
        class: Axipi\BackendBundle\Controller\WidgetController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_core_manager_item"
            - "@axipi_core_manager_language"
            - "@axipi_core_manager_component"
            - "@axipi_core_manager_relation"
            - "@axipi_core_manager_zone"

    axipi_backend_controller_relation:
        class: Axipi\BackendBundle\Controller\RelationController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_core_manager_item"
            - "@axipi_core_manager_relation"

    axipi_backend_controller_zone:
        class: Axipi\BackendBundle\Controller\ZoneController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_core_manager_zone"

    axipi_backend_controller_language:
        class: Axipi\BackendBundle\Controller\LanguageController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_core_manager_language"

    axipi_backend_controller_user:
        class: Axipi\BackendBundle\Controller\UserController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_core_manager_user"

    axipi_backend_controller_file:
        class: Axipi\BackendBundle\Controller\FileController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_core_manager_file"

    axipi_backend_controller_info:
        class: Axipi\BackendBundle\Controller\InfoController
        parent: "axipi_core_controller_abstract"

    axipi_backend_eventlistener_language:
        class: Axipi\BackendBundle\EventListener\LanguageListener
        arguments:
            - "@axipi_core_manager_item"
            - "@axipi_core_manager_component"
        tags:
            - { name: "kernel.event_listener", event: "language.after_persist", method: "persist" }

    axipi_backend_controller_comment:
        class: Axipi\BackendBundle\Controller\CommentController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_core_manager_comment"
            - "@axipi_core_manager_item"
