services:
    axipi_backend_controller_login:
        class: Axipi\BackendBundle\Controller\LoginController
        parent: "axipi_core_controller_abstract"

    axipi_backend_controller_home:
        class: Axipi\BackendBundle\Controller\HomeController
        parent: "axipi_core_controller_abstract"

    axipi_backend_controller_component:
        class: Axipi\BackendBundle\Controller\ComponentController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_backend_manager_component"

    axipi_backend_manager_component:
        class: Axipi\BackendBundle\Manager\ComponentManager
        parent: "axipi_core_manager_abstract"
        public: false

    axipi_backend_controller_page:
        class: Axipi\BackendBundle\Controller\PageController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_backend_manager_page"
            - "@axipi_backend_manager_component"

    axipi_backend_manager_page:
        class: Axipi\BackendBundle\Manager\PageManager
        parent: "axipi_core_manager_abstract"
        public: false

    axipi_backend_controller_widget:
        class: Axipi\BackendBundle\Controller\WidgetController
        parent: "axipi_core_controller_abstract"
        arguments:
            - "@axipi_backend_manager_widget"
            - "@axipi_backend_manager_component"

    axipi_backend_manager_widget:
        class: Axipi\BackendBundle\Manager\WidgetManager
        parent: "axipi_core_manager_abstract"
        public: false
