services:
    backend.home_controller:
        parent: "core.controller.abstract"
        class: Project29k\BackendBundle\Controller\HomeController

    backend.type_controller:
        parent: "core.controller.abstract"
        class: Project29k\BackendBundle\Controller\TypeController
        arguments:
            - "@type.manager"

    type.manager:
        parent: "core.manager.abstract"
        class: Project29k\BackendBundle\Manager\TypeManager
        public: false
