services:
    backend.home_controller:
        class: Project29k\BackendBundle\Controller\HomeController
        arguments:
            - "@form.factory"
        calls:
            - [ "setEngineInterface", [ "@templating" ] ]

    backend.type_controller:
        class: Project29k\BackendBundle\Controller\TypeController
        arguments:
            - "@type.manager"
        calls:
            - [ "setEngineInterface", [ "@templating" ] ]

    type.manager:
        parent: "core.manager.abstract"
        class: Project29k\BackendBundle\Manager\TypeManager
        public: false
